'use strict'

const ERROR_CLASSIFICATIONS = {
  GENERIC: 'ERROR',
  VALIDATION: 'VALIDATION_ERROR',
  INTERNAL_SERVER: 'INTERNAL_SERVER_ERROR',
  API_CALL: 'API_CALL_ERROR',
  CONNECTION: 'CONNECTION_ERROR',
  AUTHENTICATION: 'AUTHENTICATION_ERROR',
  AUTHORIZATION: 'AUTHORIZATION_ERROR',
  CRYTOGRAPHIC: 'CRYTOGRAPHIC_ERROR',
  DATABASE: 'DATABASE_ERROR'
}

export default ERROR_CLASSIFICATIONS
